config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'

  Rails.application.routes.draw do
    devise_for :users
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :quotes, only: [:new, :create, :destroy]
  resources :votes, only: [:new, :create]
  resources :mailer, only: [:new]

  root to: "quotes#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord

  belongs_to :user

  before_validation :set_score, on: :create

  validates :label, presence: true

  private

  def set_score
    self.score = (Quote.maximum(:score)|| 0) + 1
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/mailer_controller.rb
class MailerController < ApplicationController
  def new

  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save
      redirect_to new_quote_path
    else
      render :new
    end
  end

  def destroy
    Quote.find_by(id: params[:id]).destroy
    redirect_to new_quote_path, :notice => "Your quote has been deleted"
  end

  def quote_params
    params.require(:quote).permit(:label, :user_id, :score)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    user_quotes = Quote.all.where(user_id: current_user.id)
    return redirect_to root_path if user_quotes.count < 2
    return redirect_to root_path if (cookies[:clicks].to_i + 1) > 10

    quote_1 = user_quotes.order('RANDOM()').first
    quote_2 = user_quotes.where.not(id: quote_1.id).order('RANDOM()').first
    @clicks = cookies[:clicks] || 0
    @vote_form_left = VoteForm.new(preferred_quote_id: quote_1.id, other_quote_id: quote_2.id)
    @vote_form_right = VoteForm.new(preferred_quote_id: quote_2.id, other_quote_id: quote_1.id)
  end

  def create
    count_visits
    VoteForm.new(params[:vote]).save
    redirect_to new_vote_path
  end

  def count_visits
    value = (cookies[:clicks] || 0 ).to_i
    cookies[:clicks] = {:value => value + 1, :expires => Time.now + 10.second}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeasCloud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <h1>User: <%= (current_user.id) -2 %></h1>
  <br>
    <ul>
      <li><%= link_to 'Vote now!', new_vote_path %></li>
      <li><%= link_to 'Quote now!', new_quote_path %></li>
      <li><%= link_to 'Print now!', new_mailer_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out',  destroy_user_session_path, method: :delete%></li>
      <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
      <% end %>
    </ul>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/quotes/new.html.erb
<h1>Quotes</h1>

<% if @quote.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quote.errors.count, "error") %> stopped this from going on </h2>

    <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @quote do |f|%>
  <%= f.text_field :label %>
  <div>
    <%= f.text_field :user_id,
                     id: :quote_user_id,
                     value: current_user.id,
                     type: :hidden
    %>
  </div>
  <%= f.submit 'Add' %>
<% end %>

<br>
<% user_quotes = Quote.all.where(user_id: current_user.id) %>
<% lowest_score = user_quotes.minimum(:score) %>
<% if user_quotes.count > 3 %>
  <p>Do you want to delete this quote?</p>
  <p> <%= Quote.find_by(score: lowest_score).label%> </p>
  <p><%= link_to "Delete", Quote.find_by(score: lowest_score), :confirm => "Are you sure?", :method => :delete %></p>
<% end %>

app/views/votes/new.html.erb
<%= form_with model:@vote_form_left, url: votes_path do |f|%>
  <h2><%= @vote_form_left.preferred_vote_label %>></h2>
  <%= f.hidden_field :preferred_quote_id %>
  <%= f.hidden_field :other_quote_id %>
  <%= f.submit "This one" %>
<% end %>

<%= form_with model:@vote_form_right, url: votes_path do |f|%>
  <h2><%= @vote_form_right.preferred_vote_label %>></h2>
  <%= f.hidden_field :preferred_quote_id %>
  <%= f.hidden_field :other_quote_id %>
  <%= f.submit "This one" %>
<% end %>

<h2> klimknąłeś <%= @clicks %></h2>